menu:
  Home: /
  Archives: archives
  page:
    About: about

excerpt_link: Continue â†’

mathjax: true
fancybox: true

social:
  twitter: true
  github: true
  rss: true

twitter:
  username: kaumac

github:
  username: kaumac

addit:
  facebook: true
  twitter: true
  gplus: true
  pinit: true
  publid: